Fix "index out of range" error while getting IP
alexellis/faas-containerd pull request #25
Opened 2020-01-13 23:18 UTC by carlosedp

## Description

When getting IP for the created container, if the host does not has eth0
as the default network interface, the "index out of range" error is
generated.
This gets the correct interface for the namespace of the container PID.

## Motivation and Context

- [ ] I have raised an issue to propose this change **this is required**

This fixes the error on issue #24 .

## How Has This Been Tested?

Tested on a host where the default network interface is `eth1` that generated the reported error. With this fix, the IP is returned correctly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-01-14 19:46 UTC, alexellis commented on handlers/deploy.go
> +				log.Printf("%s has IP: %s.\n", name, &ipConfig.IP)
Wait, why aren't we doing a break out of the loops here?

2020-01-14 19:47 UTC, alexellis commented on handlers/deploy.go
> +		}
Let's discover the IP in the loop, then act on it after the loop, either from breaking out or from finishing without a result.

2020-01-14 19:54 UTC, alexellis requested changes
The network discovery could be improved. Please can you extract it to its own function before merge.

2020-01-15 17:34 UTC, carlosedp commented
This has been replaced by the refactor on PR #26

2020-01-15 17:34 UTC, closed without merging